version: '3.3'
services:
    urban_api:
      build: ./out_api/urban_api
      image: erwankerbrat/urban_api
      ports:
        - "1241:5000" 
      environment:
        DATABASE_URL: "mysql://root:rootpassword@db:3306/db_test"
#    urban_front:
#      build: ./out_react/urban_front
#      image: erwankerbrat/urban_front
#      ports:
#        - "1243:3000" 
    api_mail_sender:
      image: erwankerbrat/neo_api_mail_sender
      ports: 
        - "1244:5003"
    db:
      image: mysql:5.7
      volumes:
       - ./data-init:/docker-entrypoint-initdb.d  
      environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: db_test
          MYSQL_USER: username
          MYSQL_PASSWORD: password
    dbadmin:
      image: phpmyadmin/phpmyadmin:edge-4.9
      environment:
          PMA_ARBITRARY: 1
          PMA_HOST: db
          #MPA_PORT: 3306
          PMA_USER: root 
          PMA_PASSWORD: rootpassword 
      ports:
        - "1242:80" 